name = "comments-garden"
main = "src/index.ts"
compatibility_date = "2024-03-20"

[[d1_databases]]
binding = "DB"
database_name = "comments-db7"
database_id = "9f60be23-43ef-4774-a030-fe441077b457"

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
ALLOWED_ORIGINS = "https://ifard.ir"