name = "comments-garden"
main = "src/index.ts"
compatibility_date = "2024-03-20"

[[d1_databases]]
binding = "DB"
database_name = "comments-db6"
database_id = "0862f415-ac43-43c8-aefa-819a064c1544"

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
ALLOWED_ORIGINS = "https://ifard.ir"